name: Build Docs
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:

jobs:
  build-docs:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Install Material for MkDocs Insiders
        run: python3.8 -m pip install mkdocs-material
      - name: Python is python3.8
        run: alias python=python3.8
      - name: Build Docs
        run: |
          make install
          make docs
      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v1.1.5
        with:
          publish-dir: './site'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          enable-commit-comment: false
          alias: pydantic
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
